name: Build and Release

on:
  push:
    branches:
      - main
    paths:
      - 'apps/www/public/registry/index.json'
      - 'packages/cli/**'

permissions:
  contents: write
  pull-requests: read

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci
        working-directory: packages/cli

      - name: Build package
        run: npm run build
        working-directory: packages/cli

      - name: Get version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
        working-directory: packages/cli

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ steps.package-version.outputs.version }} \
            --title "Release v${{ steps.package-version.outputs.version }}" \
            --generate-notes

      - name: Publish to npm
        run: npm publish
        working-directory: packages/cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}